### ISSUE TITLE
Drop autotools

### ISSUE THREAD

**Issue by duck2** [KarthikNayak/BingWallpaper#2]
Hello.

Not to be offensive, but your project is very short(~160 lines), high-level and OS-agnostic. A simple `Makefile` of, say,

```
all: bingit

bingit: src/*.c
    gcc -o bingit src/*.c
```

would easily suffice. Why add the GNU autotools dependency? `configure` alone is more than 6000 lines.

**Comment by KarthikNayak** [comment]
Because of the dependency in feh. `configure` ensures that feh is installed.

**Comment by duck2** [comment]
There is always `which` to check if a program is installed, like `which feh || (echo "please install feh && exit 1)` 

Furthermore, people will find out they need `feh` when they see `feh: command not found`. Your main dependency here is `libcurl` which is not mentioned anywhere. Instead of bundling autoconf and automake which is at least 40x the project size just to acknowledge the dependencies, it is much more easier to instruct people to

```
git clone <repository>
sudo apt install feh libcurl4-gnutls-dev
make
```

**Comment by KarthikNayak** [comment]
@libduck2 That's a good point indeed, I mostly used autoconf to learn it, but the pros against it are a lot more. Will you do it (pull request) or shall I do it myself?
